### ISSUE TITLE
startup.vbs fails to find the correct cdrom letter 

### ISSUE THREAD

**Issue by andreacuozzo** [RomanBogachev/one-context#1]
Hi,

I'm testing the Windows context part, it seems the startup.vbs script fails to find the CD letter, even if it exists and it has the right volume name CONTEXT. The following "if test" might be wrong:

If NOT Len(driveLetter) Then
    driveLetter = "C:"
End If

others on the Internet are facing the same issue

https://forum.opennebula.org/t/windows-contextualization-problem/579

**Comment by RomanBogachev** [comment]
Sorry, but i I have not tried Windows scripts. They are default from official docs.
Later, i think, i`ll do it.
